/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ObscuraDealRoom {
  export type DealMetadataStruct = {
    title: string;
    category: string;
    maturityDate: BigNumberish;
    description: string;
    documentHash: string;
  };

  export type DealMetadataStructOutput = [
    title: string,
    category: string,
    maturityDate: bigint,
    description: string,
    documentHash: string
  ] & {
    title: string;
    category: string;
    maturityDate: bigint;
    description: string;
    documentHash: string;
  };

  export type BidStruct = {
    sealedBid: BytesLike;
    amount: BytesLike;
    claimed: boolean;
    requestId: BigNumberish;
  };

  export type BidStructOutput = [
    sealedBid: string,
    amount: string,
    claimed: boolean,
    requestId: bigint
  ] & {
    sealedBid: string;
    amount: string;
    claimed: boolean;
    requestId: bigint;
  };

  export type DealStruct = {
    issuer: AddressLike;
    metadata: ObscuraDealRoom.DealMetadataStruct;
    state: BigNumberish;
    totalCommitted: BytesLike;
    totalRepaid: BytesLike;
    totalClaimed: BytesLike;
  };

  export type DealStructOutput = [
    issuer: string,
    metadata: ObscuraDealRoom.DealMetadataStructOutput,
    state: bigint,
    totalCommitted: string,
    totalRepaid: string,
    totalClaimed: string
  ] & {
    issuer: string;
    metadata: ObscuraDealRoom.DealMetadataStructOutput;
    state: bigint;
    totalCommitted: string;
    totalRepaid: string;
    totalClaimed: string;
  };
}

export interface ObscuraDealRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimableDepositRequest"
      | "claimableRedeemRequest"
      | "closeDeal"
      | "confidentialToken"
      | "createDeal"
      | "getBidForInvestor"
      | "getDeal"
      | "getDealsCount"
      | "grantAuditorAccess"
      | "hasAuditorAccess"
      | "identityRegistry"
      | "pendingDepositRequest"
      | "pendingRedeemRequest"
      | "repay"
      | "requestDeposit"
      | "requestRedeem"
      | "setFunded"
      | "setFundingOpen"
      | "submitBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditorAccessGranted"
      | "BidSubmitted"
      | "Claimed"
      | "DealCreated"
      | "DealStateUpdated"
      | "DepositRequest"
      | "RedeemRequest"
      | "RepaymentSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimableDepositRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableRedeemRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createDeal",
    values: [ObscuraDealRoom.DealMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidForInvestor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDealsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAuditorAccess",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuditorAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDepositRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedeemRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeposit",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRedeem",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFunded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFundingOpen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableRedeemRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBidForInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDealsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAuditorAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuditorAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedeemRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFunded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFundingOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
}

export namespace AuditorAccessGrantedEvent {
  export type InputTuple = [dealId: BigNumberish, auditor: AddressLike];
  export type OutputTuple = [dealId: bigint, auditor: string];
  export interface OutputObject {
    dealId: bigint;
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    investor: AddressLike,
    sealedBid: BytesLike
  ];
  export type OutputTuple = [
    dealId: bigint,
    investor: string,
    sealedBid: string
  ];
  export interface OutputObject {
    dealId: bigint;
    investor: string;
    sealedBid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    investor: AddressLike,
    amountHandle: BytesLike
  ];
  export type OutputTuple = [
    dealId: bigint,
    investor: string,
    amountHandle: string
  ];
  export interface OutputObject {
    dealId: bigint;
    investor: string;
    amountHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCreatedEvent {
  export type InputTuple = [dealId: BigNumberish, issuer: AddressLike];
  export type OutputTuple = [dealId: bigint, issuer: string];
  export interface OutputObject {
    dealId: bigint;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealStateUpdatedEvent {
  export type InputTuple = [dealId: BigNumberish, state: BigNumberish];
  export type OutputTuple = [dealId: bigint, state: bigint];
  export interface OutputObject {
    dealId: bigint;
    state: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositRequestEvent {
  export type InputTuple = [
    controller: AddressLike,
    owner: AddressLike,
    requestId: BigNumberish,
    sender: AddressLike,
    assets: BigNumberish
  ];
  export type OutputTuple = [
    controller: string,
    owner: string,
    requestId: bigint,
    sender: string,
    assets: bigint
  ];
  export interface OutputObject {
    controller: string;
    owner: string;
    requestId: bigint;
    sender: string;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRequestEvent {
  export type InputTuple = [
    controller: AddressLike,
    owner: AddressLike,
    requestId: BigNumberish,
    sender: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    controller: string,
    owner: string,
    requestId: bigint,
    sender: string,
    shares: bigint
  ];
  export interface OutputObject {
    controller: string;
    owner: string;
    requestId: bigint;
    sender: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentSubmittedEvent {
  export type InputTuple = [dealId: BigNumberish, amountHandle: BytesLike];
  export type OutputTuple = [dealId: bigint, amountHandle: string];
  export interface OutputObject {
    dealId: bigint;
    amountHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ObscuraDealRoom extends BaseContract {
  connect(runner?: ContractRunner | null): ObscuraDealRoom;
  waitForDeployment(): Promise<this>;

  interface: ObscuraDealRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  claimableDepositRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  claimableRedeemRequest: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  closeDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  confidentialToken: TypedContractMethod<[], [string], "view">;

  createDeal: TypedContractMethod<
    [metadata: ObscuraDealRoom.DealMetadataStruct],
    [bigint],
    "nonpayable"
  >;

  getBidForInvestor: TypedContractMethod<
    [dealId: BigNumberish, investor: AddressLike],
    [ObscuraDealRoom.BidStructOutput],
    "view"
  >;

  getDeal: TypedContractMethod<
    [dealId: BigNumberish],
    [ObscuraDealRoom.DealStructOutput],
    "view"
  >;

  getDealsCount: TypedContractMethod<[], [bigint], "view">;

  grantAuditorAccess: TypedContractMethod<
    [dealId: BigNumberish, auditor: AddressLike, investor: AddressLike],
    [void],
    "nonpayable"
  >;

  hasAuditorAccess: TypedContractMethod<
    [dealId: BigNumberish, auditor: AddressLike],
    [boolean],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  pendingDepositRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  pendingRedeemRequest: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  repay: TypedContractMethod<
    [dealId: BigNumberish, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  requestDeposit: TypedContractMethod<
    [assets: BigNumberish, controller: AddressLike, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;

  requestRedeem: TypedContractMethod<
    [shares: BigNumberish, controller: AddressLike, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;

  setFunded: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  setFundingOpen: TypedContractMethod<
    [dealId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [
      dealId: BigNumberish,
      sealedBid: BytesLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableDepositRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimableRedeemRequest"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createDeal"
  ): TypedContractMethod<
    [metadata: ObscuraDealRoom.DealMetadataStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBidForInvestor"
  ): TypedContractMethod<
    [dealId: BigNumberish, investor: AddressLike],
    [ObscuraDealRoom.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish],
    [ObscuraDealRoom.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDealsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantAuditorAccess"
  ): TypedContractMethod<
    [dealId: BigNumberish, auditor: AddressLike, investor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAuditorAccess"
  ): TypedContractMethod<
    [dealId: BigNumberish, auditor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingDepositRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRedeemRequest"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [dealId: BigNumberish, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestDeposit"
  ): TypedContractMethod<
    [assets: BigNumberish, controller: AddressLike, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish, controller: AddressLike, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFunded"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFundingOpen"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      dealId: BigNumberish,
      sealedBid: BytesLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuditorAccessGranted"
  ): TypedContractEvent<
    AuditorAccessGrantedEvent.InputTuple,
    AuditorAccessGrantedEvent.OutputTuple,
    AuditorAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DealCreated"
  ): TypedContractEvent<
    DealCreatedEvent.InputTuple,
    DealCreatedEvent.OutputTuple,
    DealCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DealStateUpdated"
  ): TypedContractEvent<
    DealStateUpdatedEvent.InputTuple,
    DealStateUpdatedEvent.OutputTuple,
    DealStateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositRequest"
  ): TypedContractEvent<
    DepositRequestEvent.InputTuple,
    DepositRequestEvent.OutputTuple,
    DepositRequestEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRequest"
  ): TypedContractEvent<
    RedeemRequestEvent.InputTuple,
    RedeemRequestEvent.OutputTuple,
    RedeemRequestEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentSubmitted"
  ): TypedContractEvent<
    RepaymentSubmittedEvent.InputTuple,
    RepaymentSubmittedEvent.OutputTuple,
    RepaymentSubmittedEvent.OutputObject
  >;

  filters: {
    "AuditorAccessGranted(uint256,address)": TypedContractEvent<
      AuditorAccessGrantedEvent.InputTuple,
      AuditorAccessGrantedEvent.OutputTuple,
      AuditorAccessGrantedEvent.OutputObject
    >;
    AuditorAccessGranted: TypedContractEvent<
      AuditorAccessGrantedEvent.InputTuple,
      AuditorAccessGrantedEvent.OutputTuple,
      AuditorAccessGrantedEvent.OutputObject
    >;

    "BidSubmitted(uint256,address,bytes32)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "Claimed(uint256,address,bytes32)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "DealCreated(uint256,address)": TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;
    DealCreated: TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;

    "DealStateUpdated(uint256,uint8)": TypedContractEvent<
      DealStateUpdatedEvent.InputTuple,
      DealStateUpdatedEvent.OutputTuple,
      DealStateUpdatedEvent.OutputObject
    >;
    DealStateUpdated: TypedContractEvent<
      DealStateUpdatedEvent.InputTuple,
      DealStateUpdatedEvent.OutputTuple,
      DealStateUpdatedEvent.OutputObject
    >;

    "DepositRequest(address,address,uint256,address,uint256)": TypedContractEvent<
      DepositRequestEvent.InputTuple,
      DepositRequestEvent.OutputTuple,
      DepositRequestEvent.OutputObject
    >;
    DepositRequest: TypedContractEvent<
      DepositRequestEvent.InputTuple,
      DepositRequestEvent.OutputTuple,
      DepositRequestEvent.OutputObject
    >;

    "RedeemRequest(address,address,uint256,address,uint256)": TypedContractEvent<
      RedeemRequestEvent.InputTuple,
      RedeemRequestEvent.OutputTuple,
      RedeemRequestEvent.OutputObject
    >;
    RedeemRequest: TypedContractEvent<
      RedeemRequestEvent.InputTuple,
      RedeemRequestEvent.OutputTuple,
      RedeemRequestEvent.OutputObject
    >;

    "RepaymentSubmitted(uint256,bytes32)": TypedContractEvent<
      RepaymentSubmittedEvent.InputTuple,
      RepaymentSubmittedEvent.OutputTuple,
      RepaymentSubmittedEvent.OutputObject
    >;
    RepaymentSubmitted: TypedContractEvent<
      RepaymentSubmittedEvent.InputTuple,
      RepaymentSubmittedEvent.OutputTuple,
      RepaymentSubmittedEvent.OutputObject
    >;
  };
}
