/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICompliance__factory } from "./ICompliance__factory";
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
