/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "identity"
      | "isVerified"
      | "registerIdentity"
      | "revokeIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "IdentityRegistered" | "IdentityRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIdentity",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIdentity",
    data: BytesLike
  ): Result;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [investor: AddressLike, identityHash: BytesLike];
  export type OutputTuple = [investor: string, identityHash: string];
  export interface OutputObject {
    investor: string;
    identityHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRevokedEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  identity: TypedContractMethod<[investor: AddressLike], [string], "view">;

  isVerified: TypedContractMethod<[investor: AddressLike], [boolean], "view">;

  registerIdentity: TypedContractMethod<
    [investor: AddressLike, identityHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeIdentity: TypedContractMethod<
    [investor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[investor: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [investor: AddressLike, identityHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIdentity"
  ): TypedContractMethod<[investor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRevoked"
  ): TypedContractEvent<
    IdentityRevokedEvent.InputTuple,
    IdentityRevokedEvent.OutputTuple,
    IdentityRevokedEvent.OutputObject
  >;

  filters: {
    "IdentityRegistered(address,bytes32)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRevoked(address)": TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;
    IdentityRevoked: TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;
  };
}
