/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICompliance } from "./ICompliance";
export type { IIdentityRegistry } from "./IIdentityRegistry";
