/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IERC7540Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimableDepositRequest"
      | "claimableRedeemRequest"
      | "pendingDepositRequest"
      | "pendingRedeemRequest"
      | "requestDeposit"
      | "requestRedeem"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DepositRequest" | "RedeemRequest"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimableDepositRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableRedeemRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDepositRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedeemRequest",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeposit",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRedeem",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimableDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableRedeemRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedeemRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRedeem",
    data: BytesLike
  ): Result;
}

export namespace DepositRequestEvent {
  export type InputTuple = [
    controller: AddressLike,
    owner: AddressLike,
    requestId: BigNumberish,
    sender: AddressLike,
    assets: BigNumberish
  ];
  export type OutputTuple = [
    controller: string,
    owner: string,
    requestId: bigint,
    sender: string,
    assets: bigint
  ];
  export interface OutputObject {
    controller: string;
    owner: string;
    requestId: bigint;
    sender: string;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRequestEvent {
  export type InputTuple = [
    controller: AddressLike,
    owner: AddressLike,
    requestId: BigNumberish,
    sender: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    controller: string,
    owner: string,
    requestId: bigint,
    sender: string,
    shares: bigint
  ];
  export interface OutputObject {
    controller: string;
    owner: string;
    requestId: bigint;
    sender: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC7540 extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7540;
  waitForDeployment(): Promise<this>;

  interface: IERC7540Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimableDepositRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  claimableRedeemRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  pendingDepositRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  pendingRedeemRequest: TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;

  requestDeposit: TypedContractMethod<
    [assets: BigNumberish, controller: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  requestRedeem: TypedContractMethod<
    [shares: BigNumberish, controller: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimableDepositRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimableRedeemRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingDepositRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRedeemRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, controller: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestDeposit"
  ): TypedContractMethod<
    [assets: BigNumberish, controller: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRedeem"
  ): TypedContractMethod<
    [shares: BigNumberish, controller: AddressLike, owner: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "DepositRequest"
  ): TypedContractEvent<
    DepositRequestEvent.InputTuple,
    DepositRequestEvent.OutputTuple,
    DepositRequestEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRequest"
  ): TypedContractEvent<
    RedeemRequestEvent.InputTuple,
    RedeemRequestEvent.OutputTuple,
    RedeemRequestEvent.OutputObject
  >;

  filters: {
    "DepositRequest(address,address,uint256,address,uint256)": TypedContractEvent<
      DepositRequestEvent.InputTuple,
      DepositRequestEvent.OutputTuple,
      DepositRequestEvent.OutputObject
    >;
    DepositRequest: TypedContractEvent<
      DepositRequestEvent.InputTuple,
      DepositRequestEvent.OutputTuple,
      DepositRequestEvent.OutputObject
    >;

    "RedeemRequest(address,address,uint256,address,uint256)": TypedContractEvent<
      RedeemRequestEvent.InputTuple,
      RedeemRequestEvent.OutputTuple,
      RedeemRequestEvent.OutputObject
    >;
    RedeemRequest: TypedContractEvent<
      RedeemRequestEvent.InputTuple,
      RedeemRequestEvent.OutputTuple,
      RedeemRequestEvent.OutputObject
    >;
  };
}
