/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INoxCompute,
  INoxComputeInterface,
} from "../../../../../@iexec-nox/nox-protocol-contracts/contracts/interfaces/INoxCompute";

const _abi = [
  {
    inputs: [],
    name: "IncompatibleTypes",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidEmptyBytes",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "InvalidProof",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "NotAllowed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "NotPubliclyDecryptable",
    type: "error",
  },
  {
    inputs: [],
    name: "PublicHandleACLForbidden",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "UnauthorizedSender",
    type: "error",
  },
  {
    inputs: [],
    name: "UndefinedHandle",
    type: "error",
  },
  {
    inputs: [],
    name: "UnsupportedType",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Add",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "Allowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "balanceFrom",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "totalSupply",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newBalanceFrom",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newTotalSupply",
        type: "bytes32",
      },
    ],
    name: "Burn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Div",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Eq",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newGateway",
        type: "address",
      },
    ],
    name: "GatewayUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Ge",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Gt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "newKmsPublicKey",
        type: "bytes",
      },
    ],
    name: "KmsPublicKeyUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Le",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Lt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "MarkedAsPubliclyDecryptable",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "balanceTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "totalSupply",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newBalanceTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newTotalSupply",
        type: "bytes32",
      },
    ],
    name: "Mint",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Mul",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Ne",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newDuration",
        type: "uint256",
      },
    ],
    name: "ProofExpirationDurationUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "SafeAdd",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "numerator",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "denominator",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "SafeDiv",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "SafeMul",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "SafeSub",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "condition",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "ifTrue",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "ifFalse",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Select",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "Sub",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "balanceFrom",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "balanceTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newBalanceFrom",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newBalanceTo",
        type: "bytes32",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "viewer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "ViewerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "plaintext",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum TEEType",
        name: "toType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    name: "WrapAsPublicHandle",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "add",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "viewer",
        type: "address",
      },
    ],
    name: "addViewer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "allowPublicDecryption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allowTransient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "balanceFrom",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "totalSupply",
        type: "bytes32",
      },
    ],
    name: "burn",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newBalanceFrom",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newTotalSupply",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "disallowTransient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "numerator",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "denominator",
        type: "bytes32",
      },
    ],
    name: "div",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "eq",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gateway",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "ge",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "gt",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "isPubliclyDecryptable",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "viewer",
        type: "address",
      },
    ],
    name: "isViewer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kmsPublicKey",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "le",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "lt",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "balanceTo",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "totalSupply",
        type: "bytes32",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newBalanceTo",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newTotalSupply",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "mul",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "ne",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "proofExpirationDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "safeAdd",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "numerator",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "denominator",
        type: "bytes32",
      },
    ],
    name: "safeDiv",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "safeMul",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "safeSub",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "condition",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifTrue",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifFalse",
        type: "bytes32",
      },
    ],
    name: "select",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "gatewayAddress",
        type: "address",
      },
    ],
    name: "setGateway",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "newKmsPublicKey",
        type: "bytes",
      },
    ],
    name: "setKmsPublicKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newDuration",
        type: "uint256",
      },
    ],
    name: "setProofExpirationDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leftHandOperand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rightHandOperand",
        type: "bytes32",
      },
    ],
    name: "sub",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "balanceFrom",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "balanceTo",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bytes32",
        name: "success",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newBalanceFrom",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newBalanceTo",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "handles",
        type: "bytes32[]",
      },
    ],
    name: "validateAllowedForAll",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "decryptionProof",
        type: "bytes",
      },
    ],
    name: "validateDecryptionProof",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "enum TEEType",
        name: "teeType",
        type: "uint8",
      },
    ],
    name: "validateInputProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "value",
        type: "bytes32",
      },
      {
        internalType: "enum TEEType",
        name: "teeType",
        type: "uint8",
      },
    ],
    name: "wrapAsPublicHandle",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INoxCompute__factory {
  static readonly abi = _abi;
  static createInterface(): INoxComputeInterface {
    return new Interface(_abi) as INoxComputeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INoxCompute {
    return new Contract(address, _abi, runner) as unknown as INoxCompute;
  }
}
