/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as noxConfidentialContracts from "./nox-confidential-contracts";
export type { noxConfidentialContracts };
import type * as noxProtocolContracts from "./nox-protocol-contracts";
export type { noxProtocolContracts };
