/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
export { ObscuraDealRoom__factory } from "./ObscuraDealRoom__factory";
