/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7540Deposit,
  IERC7540DepositInterface,
} from "../../../../contracts/interfaces/IERC7540.sol/IERC7540Deposit";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
    ],
    name: "DepositRequest",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    name: "claimableDepositRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "claimableAssets",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    name: "pendingDepositRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "pendingAssets",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "requestDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7540Deposit__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7540DepositInterface {
    return new Interface(_abi) as IERC7540DepositInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7540Deposit {
    return new Contract(address, _abi, runner) as unknown as IERC7540Deposit;
  }
}
