/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7540Redeem,
  IERC7540RedeemInterface,
} from "../../../../contracts/interfaces/IERC7540.sol/IERC7540Redeem";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "RedeemRequest",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    name: "claimableRedeemRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "claimableShares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
    ],
    name: "pendingRedeemRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "pendingShares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "requestRedeem",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7540Redeem__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7540RedeemInterface {
    return new Interface(_abi) as IERC7540RedeemInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7540Redeem {
    return new Contract(address, _abi, runner) as unknown as IERC7540Redeem;
  }
}
