/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC7984",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC7984__factory>;
    getContractFactory(
      name: "INoxCompute",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INoxCompute__factory>;
    getContractFactory(
      name: "Nox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nox__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ObscuraDealRoom",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ObscuraDealRoom__factory>;

    getContractAt(
      name: "IERC7984",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC7984>;
    getContractAt(
      name: "INoxCompute",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INoxCompute>;
    getContractAt(
      name: "Nox",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Nox>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ObscuraDealRoom",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ObscuraDealRoom>;

    deployContract(
      name: "IERC7984",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7984>;
    deployContract(
      name: "INoxCompute",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INoxCompute>;
    deployContract(
      name: "Nox",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nox>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ObscuraDealRoom",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ObscuraDealRoom>;

    deployContract(
      name: "IERC7984",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7984>;
    deployContract(
      name: "INoxCompute",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INoxCompute>;
    deployContract(
      name: "Nox",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nox>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ObscuraDealRoom",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ObscuraDealRoom>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
