/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface INoxComputeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "addViewer"
      | "allow"
      | "allowPublicDecryption"
      | "allowTransient"
      | "burn"
      | "disallowTransient"
      | "div"
      | "eq"
      | "gateway"
      | "ge"
      | "gt"
      | "isAllowed"
      | "isPubliclyDecryptable"
      | "isViewer"
      | "kmsPublicKey"
      | "le"
      | "lt"
      | "mint"
      | "mul"
      | "ne"
      | "proofExpirationDuration"
      | "safeAdd"
      | "safeDiv"
      | "safeMul"
      | "safeSub"
      | "select"
      | "setGateway"
      | "setKmsPublicKey"
      | "setProofExpirationDuration"
      | "sub"
      | "transfer"
      | "validateAllowedForAll"
      | "validateDecryptionProof"
      | "validateInputProof"
      | "wrapAsPublicHandle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Add"
      | "Allowed"
      | "Burn"
      | "Div"
      | "Eq"
      | "GatewayUpdated"
      | "Ge"
      | "Gt"
      | "KmsPublicKeyUpdated"
      | "Le"
      | "Lt"
      | "MarkedAsPubliclyDecryptable"
      | "Mint"
      | "Mul"
      | "Ne"
      | "ProofExpirationDurationUpdated"
      | "SafeAdd"
      | "SafeDiv"
      | "SafeMul"
      | "SafeSub"
      | "Select"
      | "Sub"
      | "Transfer"
      | "ViewerAdded"
      | "WrapAsPublicHandle"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addViewer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allow",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowPublicDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowTransient",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disallowTransient",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ge",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPubliclyDecryptable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isViewer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kmsPublicKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "le",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proofExpirationDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeAdd",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeDiv",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeMul",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeSub",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "select",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setKmsPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProofExpirationDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAllowedForAll",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateDecryptionProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateInputProof",
    values: [BytesLike, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapAsPublicHandle",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addViewer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowPublicDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowTransient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disallowTransient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPubliclyDecryptable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isViewer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kmsPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "le", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proofExpirationDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "safeDiv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "safeMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "safeSub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "select", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setKmsPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProofExpirationDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateAllowedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateDecryptionProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateInputProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapAsPublicHandle",
    data: BytesLike
  ): Result;
}

export namespace AddEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedEvent {
  export type InputTuple = [
    sender: AddressLike,
    account: AddressLike,
    handle: BytesLike
  ];
  export type OutputTuple = [sender: string, account: string, handle: string];
  export interface OutputObject {
    sender: string;
    account: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnEvent {
  export type InputTuple = [
    caller: AddressLike,
    balanceFrom: BytesLike,
    amount: BytesLike,
    totalSupply: BytesLike,
    success: BytesLike,
    newBalanceFrom: BytesLike,
    newTotalSupply: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    balanceFrom: string,
    amount: string,
    totalSupply: string,
    success: string,
    newBalanceFrom: string,
    newTotalSupply: string
  ];
  export interface OutputObject {
    caller: string;
    balanceFrom: string;
    amount: string;
    totalSupply: string;
    success: string;
    newBalanceFrom: string;
    newTotalSupply: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DivEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EqEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewayUpdatedEvent {
  export type InputTuple = [newGateway: AddressLike];
  export type OutputTuple = [newGateway: string];
  export interface OutputObject {
    newGateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GeEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GtEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KmsPublicKeyUpdatedEvent {
  export type InputTuple = [newKmsPublicKey: BytesLike];
  export type OutputTuple = [newKmsPublicKey: string];
  export interface OutputObject {
    newKmsPublicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LtEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarkedAsPubliclyDecryptableEvent {
  export type InputTuple = [sender: AddressLike, handle: BytesLike];
  export type OutputTuple = [sender: string, handle: string];
  export interface OutputObject {
    sender: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintEvent {
  export type InputTuple = [
    caller: AddressLike,
    balanceTo: BytesLike,
    amount: BytesLike,
    totalSupply: BytesLike,
    success: BytesLike,
    newBalanceTo: BytesLike,
    newTotalSupply: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    balanceTo: string,
    amount: string,
    totalSupply: string,
    success: string,
    newBalanceTo: string,
    newTotalSupply: string
  ];
  export interface OutputObject {
    caller: string;
    balanceTo: string;
    amount: string;
    totalSupply: string;
    success: string;
    newBalanceTo: string;
    newTotalSupply: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MulEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NeEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofExpirationDurationUpdatedEvent {
  export type InputTuple = [newDuration: BigNumberish];
  export type OutputTuple = [newDuration: bigint];
  export interface OutputObject {
    newDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafeAddEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    success: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    success: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    success: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafeDivEvent {
  export type InputTuple = [
    caller: AddressLike,
    numerator: BytesLike,
    denominator: BytesLike,
    success: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    numerator: string,
    denominator: string,
    success: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    numerator: string;
    denominator: string;
    success: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafeMulEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    success: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    success: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    success: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafeSubEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    success: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    success: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    success: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SelectEvent {
  export type InputTuple = [
    caller: AddressLike,
    condition: BytesLike,
    ifTrue: BytesLike,
    ifFalse: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    condition: string,
    ifTrue: string,
    ifFalse: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    condition: string;
    ifTrue: string;
    ifFalse: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubEvent {
  export type InputTuple = [
    caller: AddressLike,
    leftHandOperand: BytesLike,
    rightHandOperand: BytesLike,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    leftHandOperand: string,
    rightHandOperand: string,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    leftHandOperand: string;
    rightHandOperand: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    caller: AddressLike,
    balanceFrom: BytesLike,
    balanceTo: BytesLike,
    amount: BytesLike,
    success: BytesLike,
    newBalanceFrom: BytesLike,
    newBalanceTo: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    balanceFrom: string,
    balanceTo: string,
    amount: string,
    success: string,
    newBalanceFrom: string,
    newBalanceTo: string
  ];
  export interface OutputObject {
    caller: string;
    balanceFrom: string;
    balanceTo: string;
    amount: string;
    success: string;
    newBalanceFrom: string;
    newBalanceTo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViewerAddedEvent {
  export type InputTuple = [
    sender: AddressLike,
    viewer: AddressLike,
    handle: BytesLike
  ];
  export type OutputTuple = [sender: string, viewer: string, handle: string];
  export interface OutputObject {
    sender: string;
    viewer: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrapAsPublicHandleEvent {
  export type InputTuple = [
    caller: AddressLike,
    plaintext: BytesLike,
    toType: BigNumberish,
    result: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    plaintext: string,
    toType: bigint,
    result: string
  ];
  export interface OutputObject {
    caller: string;
    plaintext: string;
    toType: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface INoxCompute extends BaseContract {
  connect(runner?: ContractRunner | null): INoxCompute;
  waitForDeployment(): Promise<this>;

  interface: INoxComputeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  addViewer: TypedContractMethod<
    [handle: BytesLike, viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  allow: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowPublicDecryption: TypedContractMethod<
    [handle: BytesLike],
    [void],
    "nonpayable"
  >;

  allowTransient: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  burn: TypedContractMethod<
    [balanceFrom: BytesLike, amount: BytesLike, totalSupply: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceFrom: string;
        newTotalSupply: string;
      }
    ],
    "nonpayable"
  >;

  disallowTransient: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  div: TypedContractMethod<
    [numerator: BytesLike, denominator: BytesLike],
    [string],
    "nonpayable"
  >;

  eq: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  gateway: TypedContractMethod<[], [string], "view">;

  ge: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  gt: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  isAllowed: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isPubliclyDecryptable: TypedContractMethod<
    [handle: BytesLike],
    [boolean],
    "view"
  >;

  isViewer: TypedContractMethod<
    [handle: BytesLike, viewer: AddressLike],
    [boolean],
    "view"
  >;

  kmsPublicKey: TypedContractMethod<[], [string], "view">;

  le: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  lt: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  mint: TypedContractMethod<
    [balanceTo: BytesLike, amount: BytesLike, totalSupply: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceTo: string;
        newTotalSupply: string;
      }
    ],
    "nonpayable"
  >;

  mul: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  ne: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  proofExpirationDuration: TypedContractMethod<[], [bigint], "view">;

  safeAdd: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;

  safeDiv: TypedContractMethod<
    [numerator: BytesLike, denominator: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;

  safeMul: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;

  safeSub: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;

  select: TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  setGateway: TypedContractMethod<
    [gatewayAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setKmsPublicKey: TypedContractMethod<
    [newKmsPublicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  setProofExpirationDuration: TypedContractMethod<
    [newDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  sub: TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;

  transfer: TypedContractMethod<
    [balanceFrom: BytesLike, balanceTo: BytesLike, amount: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceFrom: string;
        newBalanceTo: string;
      }
    ],
    "nonpayable"
  >;

  validateAllowedForAll: TypedContractMethod<
    [account: AddressLike, handles: BytesLike[]],
    [void],
    "view"
  >;

  validateDecryptionProof: TypedContractMethod<
    [handle: BytesLike, decryptionProof: BytesLike],
    [string],
    "view"
  >;

  validateInputProof: TypedContractMethod<
    [
      handle: BytesLike,
      owner: AddressLike,
      proof: BytesLike,
      teeType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  wrapAsPublicHandle: TypedContractMethod<
    [value: BytesLike, teeType: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addViewer"
  ): TypedContractMethod<
    [handle: BytesLike, viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allow"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowPublicDecryption"
  ): TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowTransient"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [balanceFrom: BytesLike, amount: BytesLike, totalSupply: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceFrom: string;
        newTotalSupply: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disallowTransient"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div"
  ): TypedContractMethod<
    [numerator: BytesLike, denominator: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ge"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPubliclyDecryptable"
  ): TypedContractMethod<[handle: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isViewer"
  ): TypedContractMethod<
    [handle: BytesLike, viewer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kmsPublicKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "le"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [balanceTo: BytesLike, amount: BytesLike, totalSupply: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceTo: string;
        newTotalSupply: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proofExpirationDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "safeAdd"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeDiv"
  ): TypedContractMethod<
    [numerator: BytesLike, denominator: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeMul"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeSub"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [[string, string] & { success: string; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "select"
  ): TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGateway"
  ): TypedContractMethod<[gatewayAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKmsPublicKey"
  ): TypedContractMethod<[newKmsPublicKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProofExpirationDuration"
  ): TypedContractMethod<[newDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [leftHandOperand: BytesLike, rightHandOperand: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [balanceFrom: BytesLike, balanceTo: BytesLike, amount: BytesLike],
    [
      [string, string, string] & {
        success: string;
        newBalanceFrom: string;
        newBalanceTo: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateAllowedForAll"
  ): TypedContractMethod<
    [account: AddressLike, handles: BytesLike[]],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateDecryptionProof"
  ): TypedContractMethod<
    [handle: BytesLike, decryptionProof: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateInputProof"
  ): TypedContractMethod<
    [
      handle: BytesLike,
      owner: AddressLike,
      proof: BytesLike,
      teeType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapAsPublicHandle"
  ): TypedContractMethod<
    [value: BytesLike, teeType: BigNumberish],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "Add"
  ): TypedContractEvent<
    AddEvent.InputTuple,
    AddEvent.OutputTuple,
    AddEvent.OutputObject
  >;
  getEvent(
    key: "Allowed"
  ): TypedContractEvent<
    AllowedEvent.InputTuple,
    AllowedEvent.OutputTuple,
    AllowedEvent.OutputObject
  >;
  getEvent(
    key: "Burn"
  ): TypedContractEvent<
    BurnEvent.InputTuple,
    BurnEvent.OutputTuple,
    BurnEvent.OutputObject
  >;
  getEvent(
    key: "Div"
  ): TypedContractEvent<
    DivEvent.InputTuple,
    DivEvent.OutputTuple,
    DivEvent.OutputObject
  >;
  getEvent(
    key: "Eq"
  ): TypedContractEvent<
    EqEvent.InputTuple,
    EqEvent.OutputTuple,
    EqEvent.OutputObject
  >;
  getEvent(
    key: "GatewayUpdated"
  ): TypedContractEvent<
    GatewayUpdatedEvent.InputTuple,
    GatewayUpdatedEvent.OutputTuple,
    GatewayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Ge"
  ): TypedContractEvent<
    GeEvent.InputTuple,
    GeEvent.OutputTuple,
    GeEvent.OutputObject
  >;
  getEvent(
    key: "Gt"
  ): TypedContractEvent<
    GtEvent.InputTuple,
    GtEvent.OutputTuple,
    GtEvent.OutputObject
  >;
  getEvent(
    key: "KmsPublicKeyUpdated"
  ): TypedContractEvent<
    KmsPublicKeyUpdatedEvent.InputTuple,
    KmsPublicKeyUpdatedEvent.OutputTuple,
    KmsPublicKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Le"
  ): TypedContractEvent<
    LeEvent.InputTuple,
    LeEvent.OutputTuple,
    LeEvent.OutputObject
  >;
  getEvent(
    key: "Lt"
  ): TypedContractEvent<
    LtEvent.InputTuple,
    LtEvent.OutputTuple,
    LtEvent.OutputObject
  >;
  getEvent(
    key: "MarkedAsPubliclyDecryptable"
  ): TypedContractEvent<
    MarkedAsPubliclyDecryptableEvent.InputTuple,
    MarkedAsPubliclyDecryptableEvent.OutputTuple,
    MarkedAsPubliclyDecryptableEvent.OutputObject
  >;
  getEvent(
    key: "Mint"
  ): TypedContractEvent<
    MintEvent.InputTuple,
    MintEvent.OutputTuple,
    MintEvent.OutputObject
  >;
  getEvent(
    key: "Mul"
  ): TypedContractEvent<
    MulEvent.InputTuple,
    MulEvent.OutputTuple,
    MulEvent.OutputObject
  >;
  getEvent(
    key: "Ne"
  ): TypedContractEvent<
    NeEvent.InputTuple,
    NeEvent.OutputTuple,
    NeEvent.OutputObject
  >;
  getEvent(
    key: "ProofExpirationDurationUpdated"
  ): TypedContractEvent<
    ProofExpirationDurationUpdatedEvent.InputTuple,
    ProofExpirationDurationUpdatedEvent.OutputTuple,
    ProofExpirationDurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SafeAdd"
  ): TypedContractEvent<
    SafeAddEvent.InputTuple,
    SafeAddEvent.OutputTuple,
    SafeAddEvent.OutputObject
  >;
  getEvent(
    key: "SafeDiv"
  ): TypedContractEvent<
    SafeDivEvent.InputTuple,
    SafeDivEvent.OutputTuple,
    SafeDivEvent.OutputObject
  >;
  getEvent(
    key: "SafeMul"
  ): TypedContractEvent<
    SafeMulEvent.InputTuple,
    SafeMulEvent.OutputTuple,
    SafeMulEvent.OutputObject
  >;
  getEvent(
    key: "SafeSub"
  ): TypedContractEvent<
    SafeSubEvent.InputTuple,
    SafeSubEvent.OutputTuple,
    SafeSubEvent.OutputObject
  >;
  getEvent(
    key: "Select"
  ): TypedContractEvent<
    SelectEvent.InputTuple,
    SelectEvent.OutputTuple,
    SelectEvent.OutputObject
  >;
  getEvent(
    key: "Sub"
  ): TypedContractEvent<
    SubEvent.InputTuple,
    SubEvent.OutputTuple,
    SubEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "ViewerAdded"
  ): TypedContractEvent<
    ViewerAddedEvent.InputTuple,
    ViewerAddedEvent.OutputTuple,
    ViewerAddedEvent.OutputObject
  >;
  getEvent(
    key: "WrapAsPublicHandle"
  ): TypedContractEvent<
    WrapAsPublicHandleEvent.InputTuple,
    WrapAsPublicHandleEvent.OutputTuple,
    WrapAsPublicHandleEvent.OutputObject
  >;

  filters: {
    "Add(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      AddEvent.InputTuple,
      AddEvent.OutputTuple,
      AddEvent.OutputObject
    >;
    Add: TypedContractEvent<
      AddEvent.InputTuple,
      AddEvent.OutputTuple,
      AddEvent.OutputObject
    >;

    "Allowed(address,address,bytes32)": TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;
    Allowed: TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;

    "Burn(address,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;
    Burn: TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;

    "Div(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      DivEvent.InputTuple,
      DivEvent.OutputTuple,
      DivEvent.OutputObject
    >;
    Div: TypedContractEvent<
      DivEvent.InputTuple,
      DivEvent.OutputTuple,
      DivEvent.OutputObject
    >;

    "Eq(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      EqEvent.InputTuple,
      EqEvent.OutputTuple,
      EqEvent.OutputObject
    >;
    Eq: TypedContractEvent<
      EqEvent.InputTuple,
      EqEvent.OutputTuple,
      EqEvent.OutputObject
    >;

    "GatewayUpdated(address)": TypedContractEvent<
      GatewayUpdatedEvent.InputTuple,
      GatewayUpdatedEvent.OutputTuple,
      GatewayUpdatedEvent.OutputObject
    >;
    GatewayUpdated: TypedContractEvent<
      GatewayUpdatedEvent.InputTuple,
      GatewayUpdatedEvent.OutputTuple,
      GatewayUpdatedEvent.OutputObject
    >;

    "Ge(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      GeEvent.InputTuple,
      GeEvent.OutputTuple,
      GeEvent.OutputObject
    >;
    Ge: TypedContractEvent<
      GeEvent.InputTuple,
      GeEvent.OutputTuple,
      GeEvent.OutputObject
    >;

    "Gt(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      GtEvent.InputTuple,
      GtEvent.OutputTuple,
      GtEvent.OutputObject
    >;
    Gt: TypedContractEvent<
      GtEvent.InputTuple,
      GtEvent.OutputTuple,
      GtEvent.OutputObject
    >;

    "KmsPublicKeyUpdated(bytes)": TypedContractEvent<
      KmsPublicKeyUpdatedEvent.InputTuple,
      KmsPublicKeyUpdatedEvent.OutputTuple,
      KmsPublicKeyUpdatedEvent.OutputObject
    >;
    KmsPublicKeyUpdated: TypedContractEvent<
      KmsPublicKeyUpdatedEvent.InputTuple,
      KmsPublicKeyUpdatedEvent.OutputTuple,
      KmsPublicKeyUpdatedEvent.OutputObject
    >;

    "Le(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      LeEvent.InputTuple,
      LeEvent.OutputTuple,
      LeEvent.OutputObject
    >;
    Le: TypedContractEvent<
      LeEvent.InputTuple,
      LeEvent.OutputTuple,
      LeEvent.OutputObject
    >;

    "Lt(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      LtEvent.InputTuple,
      LtEvent.OutputTuple,
      LtEvent.OutputObject
    >;
    Lt: TypedContractEvent<
      LtEvent.InputTuple,
      LtEvent.OutputTuple,
      LtEvent.OutputObject
    >;

    "MarkedAsPubliclyDecryptable(address,bytes32)": TypedContractEvent<
      MarkedAsPubliclyDecryptableEvent.InputTuple,
      MarkedAsPubliclyDecryptableEvent.OutputTuple,
      MarkedAsPubliclyDecryptableEvent.OutputObject
    >;
    MarkedAsPubliclyDecryptable: TypedContractEvent<
      MarkedAsPubliclyDecryptableEvent.InputTuple,
      MarkedAsPubliclyDecryptableEvent.OutputTuple,
      MarkedAsPubliclyDecryptableEvent.OutputObject
    >;

    "Mint(address,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;
    Mint: TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;

    "Mul(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      MulEvent.InputTuple,
      MulEvent.OutputTuple,
      MulEvent.OutputObject
    >;
    Mul: TypedContractEvent<
      MulEvent.InputTuple,
      MulEvent.OutputTuple,
      MulEvent.OutputObject
    >;

    "Ne(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      NeEvent.InputTuple,
      NeEvent.OutputTuple,
      NeEvent.OutputObject
    >;
    Ne: TypedContractEvent<
      NeEvent.InputTuple,
      NeEvent.OutputTuple,
      NeEvent.OutputObject
    >;

    "ProofExpirationDurationUpdated(uint256)": TypedContractEvent<
      ProofExpirationDurationUpdatedEvent.InputTuple,
      ProofExpirationDurationUpdatedEvent.OutputTuple,
      ProofExpirationDurationUpdatedEvent.OutputObject
    >;
    ProofExpirationDurationUpdated: TypedContractEvent<
      ProofExpirationDurationUpdatedEvent.InputTuple,
      ProofExpirationDurationUpdatedEvent.OutputTuple,
      ProofExpirationDurationUpdatedEvent.OutputObject
    >;

    "SafeAdd(address,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      SafeAddEvent.InputTuple,
      SafeAddEvent.OutputTuple,
      SafeAddEvent.OutputObject
    >;
    SafeAdd: TypedContractEvent<
      SafeAddEvent.InputTuple,
      SafeAddEvent.OutputTuple,
      SafeAddEvent.OutputObject
    >;

    "SafeDiv(address,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      SafeDivEvent.InputTuple,
      SafeDivEvent.OutputTuple,
      SafeDivEvent.OutputObject
    >;
    SafeDiv: TypedContractEvent<
      SafeDivEvent.InputTuple,
      SafeDivEvent.OutputTuple,
      SafeDivEvent.OutputObject
    >;

    "SafeMul(address,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      SafeMulEvent.InputTuple,
      SafeMulEvent.OutputTuple,
      SafeMulEvent.OutputObject
    >;
    SafeMul: TypedContractEvent<
      SafeMulEvent.InputTuple,
      SafeMulEvent.OutputTuple,
      SafeMulEvent.OutputObject
    >;

    "SafeSub(address,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      SafeSubEvent.InputTuple,
      SafeSubEvent.OutputTuple,
      SafeSubEvent.OutputObject
    >;
    SafeSub: TypedContractEvent<
      SafeSubEvent.InputTuple,
      SafeSubEvent.OutputTuple,
      SafeSubEvent.OutputObject
    >;

    "Select(address,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      SelectEvent.InputTuple,
      SelectEvent.OutputTuple,
      SelectEvent.OutputObject
    >;
    Select: TypedContractEvent<
      SelectEvent.InputTuple,
      SelectEvent.OutputTuple,
      SelectEvent.OutputObject
    >;

    "Sub(address,bytes32,bytes32,bytes32)": TypedContractEvent<
      SubEvent.InputTuple,
      SubEvent.OutputTuple,
      SubEvent.OutputObject
    >;
    Sub: TypedContractEvent<
      SubEvent.InputTuple,
      SubEvent.OutputTuple,
      SubEvent.OutputObject
    >;

    "Transfer(address,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "ViewerAdded(address,address,bytes32)": TypedContractEvent<
      ViewerAddedEvent.InputTuple,
      ViewerAddedEvent.OutputTuple,
      ViewerAddedEvent.OutputObject
    >;
    ViewerAdded: TypedContractEvent<
      ViewerAddedEvent.InputTuple,
      ViewerAddedEvent.OutputTuple,
      ViewerAddedEvent.OutputObject
    >;

    "WrapAsPublicHandle(address,bytes32,uint8,bytes32)": TypedContractEvent<
      WrapAsPublicHandleEvent.InputTuple,
      WrapAsPublicHandleEvent.OutputTuple,
      WrapAsPublicHandleEvent.OutputObject
    >;
    WrapAsPublicHandle: TypedContractEvent<
      WrapAsPublicHandleEvent.InputTuple,
      WrapAsPublicHandleEvent.OutputTuple,
      WrapAsPublicHandleEvent.OutputObject
    >;
  };
}
